# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: On Push Run

on: push

env:
  testing_github_action_DIR: testing_github_action

jobs:
  hello-world:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
    - name: Check-out devops repository
      uses: actions/checkout@v2
      with:
        repository: kbbabu/testing_github_action
        token: ${{ secrets.GITHUB_TOKEN }}
        path: ${{ env.testing_github_action_DIR }}

    - name: Hello World
      run: python ${{ env.testing_github_action_DIR }}/hello_world.py
      shell: sh
